services:
  - type: web
    name: bettermail-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn agent:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        sync: false
      - key: FORWARD_TO_EMAIL
        sync: false